### ISSUE TITLE
What is Blue Pill advanced? No idea.

### ISSUE THREAD

**Issue by ryba-xek** [sagarHackeD/STM32Bluepill_eagle#1]
Can you please elaborate on the topic?
Maybe add some description to the README.
Thanks.

**Comment by sagarHackeD** [comment]
Sorry for late response 
So here is the thing the blue pill has this 6 pin header used to select boot option which is exposed in this part(Blue Pill advanced) so that you can connect or control boot options of blue pill from another microcontroller or a remotely located switches 
To use this firstly you have to de-solder 6pin connector and solder the header on the bottom side so that the blue pill makes contact with the mother PCB which you can route to where ever you want

**Comment by sagarHackeD** [comment]
I guess thats it I'm closing the issue now
